/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ddl_example_demo_services_HelloWorldJNI */

#ifndef _Included_com_ddl_example_demo_services_HelloWorldJNI
#define _Included_com_ddl_example_demo_services_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ddl_example_demo_services_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ddl_example_demo_services_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
